### ISSUE TITLE
Error RDPoverSSH.Service encountered an error: System.InvalidOperationException: Service RDPoverSSH.Service.Worker was not found on computer '.'. 

### ISSUE THREAD

**Issue by DanoPTT** [micahmo/RDPoverSSH#4]
I install it on Windows 10 pro (64bit) ,
and when started I got error
RDPoverSSH.Service encountered an error: System.InvalidOperationException: Service RDPoverSSH.Service.Worker was not found on computer '.'. at System.ServiceProcess.ServiceController.GenerateNames() at System.ServiceProcess.ServiceController.get_ServiceName() at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess) at System.ServiceProcess.ServiceController.GenerateStatus() at System.ServiceProcess.ServiceController.get_Status() at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Uninstall(HostConfiguration`1 config, ServiceController sc) at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.<>c.<ConfigureService>b__11_3(ServiceController sc, HostConfiguration`1 cfg) at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.UsingServiceController(HostConfiguration`1 config, Action`2 action) at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.ConfigureService(HostConfiguration`1 config) at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Run(Action`1 runAction) 

SSH server is running, I can make connection to that machine using SSH. Where can be a problem?

**Comment by micahmo** [comment]
It looks like the RDPoverSSH server was not installed properly. It should be here like this.

![image](https://github.com/micahmo/RDPoverSSH/assets/7417301/221aec3b-f8b5-486e-a799-d16c8992cb60)

If you run the installer again, look for a message indicating that it's installing the service.

**Comment by DanoPTT** [comment]
Hello,

after few restarts, uninstall and install now it work. 

Before there was missing RDPPoverSSH Worker Service in services.

 

Thank you

 

Daniel Petrik

**Comment by micahmo** [comment]
Glad you got it working!!
